<?php

namespace App\Http\Controllers\Charts;

use App\Http\Controllers\Controller;
use App\Models\VWFinancialPolicy;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;

class FinancialPolicyChartsController extends Controller
{
    static public function financialPolicy($destination, $area, $dist, $loc)
    {
        switch ($destination) {
            case 'General':
                $total = VWFinancialPolicy::count();
                $area_area = VWFinancialPolicy::select(DB::raw('area, count(area)'))->groupBy('area')->get();
                $district_dist = VWFinancialPolicy::select(DB::raw('district, count(district)'))->groupBy('district')->get();
                $local_loc = VWFinancialPolicy::select(DB::raw('local, count(local)'))->groupBy('local')->get();
                $question1a = VWFinancialPolicy::select(DB::raw('fin_eva_a_question1a, count(financial_id) AS y'))->groupBy('fin_eva_a_question1a')->get();
                $fin_eva_a_comment1a = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment1a, count(fin_eva_a_comment1a)'))->groupBy('fin_eva_a_comment1a')->get();
                $question1b = VWFinancialPolicy::select(DB::raw('fin_eva_a_question1b, count(financial_id) AS y'))->groupBy('fin_eva_a_question1b')->get();
                $fin_eva_a_comment1b = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment1b, count(fin_eva_a_comment1b)'))->groupBy('fin_eva_a_comment1b')->get();
                $question1c = VWFinancialPolicy::select(DB::raw('fin_eva_a_question1c, count(financial_id) AS y'))->groupBy('fin_eva_a_question1c')->get();
                $fin_eva_a_comment1c = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment1c, count(fin_eva_a_comment1c)'))->groupBy('fin_eva_a_comment1c')->get();
                $question1d = VWFinancialPolicy::select(DB::raw('fin_eva_a_question1d, count(financial_id) AS y'))->groupBy('fin_eva_a_question1d')->get();
                $fin_eva_a_comment1d = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment1d, count(fin_eva_a_comment1d)'))->groupBy('fin_eva_a_comment1d')->get();
                $question1e = VWFinancialPolicy::select(DB::raw('fin_eva_a_question1e, count(financial_id) AS y'))->groupBy('fin_eva_a_question1e')->get();
                $fin_eva_a_comment1e = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment1e, count(fin_eva_a_comment1e)'))->groupBy('fin_eva_a_comment1e')->get();
                $question1f = VWFinancialPolicy::select(DB::raw('fin_eva_a_question1f, count(financial_id) AS y'))->groupBy('fin_eva_a_question1f')->get();
                $fin_eva_a_comment1f = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment1f, count(fin_eva_a_comment1f)'))->groupBy('fin_eva_a_comment1f')->get();
                $question1g = VWFinancialPolicy::select(DB::raw('fin_eva_a_question1g, count(financial_id) AS y'))->groupBy('fin_eva_a_question1g')->get();
                $fin_eva_a_comment1g = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment1g, count(fin_eva_a_comment1g)'))->groupBy('fin_eva_a_comment1g')->get();
                $question2a = VWFinancialPolicy::select(DB::raw('fin_eva_a_question2a, count(financial_id) AS y'))->groupBy('fin_eva_a_question2a')->get();
                $fin_eva_a_comment2a = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment2a, count(fin_eva_a_comment2a)'))->groupBy('fin_eva_a_comment2a')->get();
                $question2b = VWFinancialPolicy::select(DB::raw('fin_eva_a_question2b, count(financial_id) AS y'))->groupBy('fin_eva_a_question2b')->get();
                $fin_eva_a_comment2b = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment2b, count(fin_eva_a_comment2b)'))->groupBy('fin_eva_a_comment2b')->get();
                $question2c = VWFinancialPolicy::select(DB::raw('fin_eva_a_question2c, count(financial_id) AS y'))->groupBy('fin_eva_a_question2c')->get();
                $fin_eva_a_comment2c = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment2c, count(fin_eva_a_comment2c)'))->groupBy('fin_eva_a_comment2c')->get();
                $question3a = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3a, count(financial_id) AS y'))->groupBy('fin_eva_a_question3a')->get();
                $fin_eva_a_comment3a = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3a, count(fin_eva_a_comment3a)'))->groupBy('fin_eva_a_comment3a')->get();
                $question3b = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3b, count(financial_id) AS y'))->groupBy('fin_eva_a_question3b')->get();
                $fin_eva_a_comment3b = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3b, count(fin_eva_a_comment3b)'))->groupBy('fin_eva_a_comment3b')->get();
                $question3c = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3c, count(financial_id) AS y'))->groupBy('fin_eva_a_question3c')->get();
                $fin_eva_a_comment3c = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3c, count(fin_eva_a_comment3c)'))->groupBy('fin_eva_a_comment3c')->get();
                $question3d = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3d, count(financial_id) AS y'))->groupBy('fin_eva_a_question3d')->get();
                $fin_eva_a_comment3d = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3d, count(fin_eva_a_comment3d)'))->groupBy('fin_eva_a_comment3d')->get();
                $question3e = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3e, count(financial_id) AS y'))->groupBy('fin_eva_a_question3e')->get();
                $fin_eva_a_comment3e = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3e, count(fin_eva_a_comment3e)'))->groupBy('fin_eva_a_comment3e')->get();
                $question3f = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3f, count(financial_id) AS y'))->groupBy('fin_eva_a_question3f')->get();
                $fin_eva_a_comment3f = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3f, count(fin_eva_a_comment3f)'))->groupBy('fin_eva_a_comment3f')->get();
                $question3g = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3g, count(financial_id) AS y'))->groupBy('fin_eva_a_question3g')->get();
                $fin_eva_a_comment3g = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3g, count(fin_eva_a_comment3g)'))->groupBy('fin_eva_a_comment3g')->get();
                $question3h = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3h, count(financial_id) AS y'))->groupBy('fin_eva_a_question3h')->get();
                $fin_eva_a_comment3h = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3h, count(fin_eva_a_comment3h)'))->groupBy('fin_eva_a_comment3h')->get();
                $question3i = VWFinancialPolicy::select(DB::raw('fin_eva_a_question3i, count(financial_id) AS y'))->groupBy('fin_eva_a_question3i')->get();
                $fin_eva_a_comment3i = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment3i, count(fin_eva_a_comment3i)'))->groupBy('fin_eva_a_comment3i')->get();
                $question4a = VWFinancialPolicy::select(DB::raw('fin_eva_a_question4a, count(financial_id) AS y'))->groupBy('fin_eva_a_question4a')->get();
                $fin_eva_a_comment4a = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4a, count(fin_eva_a_comment4a)'))->groupBy('fin_eva_a_comment4a')->get();
                $fin_eva_a_comment4b = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4b, count(fin_eva_a_comment4b)'))->groupBy('fin_eva_a_comment4b')->get();
                $fin_eva_a_comment4c1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4c1, count(fin_eva_a_comment4c1)'))->groupBy('fin_eva_a_comment4c1')->get();
                $fin_eva_a_comment4c2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4c2, count(fin_eva_a_comment4c2)'))->groupBy('fin_eva_a_comment4c2')->get();
                $fin_eva_a_comment4c3 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4c3, count(fin_eva_a_comment4c3)'))->groupBy('fin_eva_a_comment4c3')->get();
                $fin_eva_a_comment4d = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4d, count(fin_eva_a_comment4d)'))->groupBy('fin_eva_a_comment4d')->get();
                $fin_eva_a_comment4e = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4e, count(fin_eva_a_comment4e)'))->groupBy('fin_eva_a_comment4e')->get();
                $fin_eva_a_comment4f = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment4f, count(fin_eva_a_comment4f)'))->groupBy('fin_eva_a_comment4f')->get();
                $fin_eva_a_comment5a = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment5a, count(fin_eva_a_comment5a)'))->groupBy('fin_eva_a_comment5a')->get();
                $fin_eva_a_comment5b1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment5b1, count(fin_eva_a_comment5b1)'))->groupBy('fin_eva_a_comment5b1')->get();
                $fin_eva_a_comment5b2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment5b2, count(fin_eva_a_comment5b2)'))->groupBy('fin_eva_a_comment5b2')->get();
                $fin_eva_a_comment5b3 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment5b3, count(fin_eva_a_comment5b3)'))->groupBy('fin_eva_a_comment5b3')->get();
                $fin_eva_a_comment5b4 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment5b4, count(fin_eva_a_comment5b4)'))->groupBy('fin_eva_a_comment5b4')->get();
                $fin_eva_a_comment5c = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment5c, count(fin_eva_a_comment5c)'))->groupBy('fin_eva_a_comment5c')->get();
                $question6a = VWFinancialPolicy::select(DB::raw('fin_eva_a_question6a, count(financial_id) AS y'))->groupBy('fin_eva_a_question6a')->get();
                $fin_eva_a_comment6a = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment6a, count(fin_eva_a_comment6a)'))->groupBy('fin_eva_a_comment6a')->get();
                $fin_eva_a_comment6b = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment6b, count(fin_eva_a_comment6b)'))->groupBy('fin_eva_a_comment6b')->get();
                $question6c1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_question6c1, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c1')->get();
                $fin_eva_a_comment6c1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment6c1, count(fin_eva_a_comment6c1)'))->groupBy('fin_eva_a_comment6c1')->get();
                $question6c2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_question6c2, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c2')->get();
                $fin_eva_a_comment6c2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment6c2, count(fin_eva_a_comment6c2)'))->groupBy('fin_eva_a_comment6c2')->get();
                $fin_eva_a_comment6c3 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment6c3, count(fin_eva_a_comment6c3)'))->groupBy('fin_eva_a_comment6c3')->get();
                $question6d = VWFinancialPolicy::select(DB::raw('fin_eva_a_question6d, count(financial_id) AS y'))->groupBy('fin_eva_a_question6d')->get();
                $fin_eva_a_comment6d = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment6d, count(fin_eva_a_comment6d)'))->groupBy('fin_eva_a_comment6d')->get();
                $question6e = VWFinancialPolicy::select(DB::raw('fin_eva_a_question6e, count(financial_id) AS y'))->groupBy('fin_eva_a_question6e')->get();
                $fin_eva_a_comment6e = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment6e, count(fin_eva_a_comment6e)'))->groupBy('fin_eva_a_comment6e')->get();
                $question7a1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_question7a1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a1')->get();
                $fin_eva_a_comment7a1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment7a1, count(fin_eva_a_comment7a1)'))->groupBy('fin_eva_a_comment7a1')->get();
                $question7a2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_question7a2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a2')->get();
                $fin_eva_a_comment7a2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment7a2, count(fin_eva_a_comment7a2)'))->groupBy('fin_eva_a_comment7a2')->get();
                $question7b1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_question7b1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b1')->get();
                $fin_eva_a_comment7b1 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment7b1, count(fin_eva_a_comment7b1)'))->groupBy('fin_eva_a_comment7b1')->get();
                $question7b2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_question7b2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b2')->get();
                $fin_eva_a_comment7b2 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment7b2, count(fin_eva_a_comment7b2)'))->groupBy('fin_eva_a_comment7b2')->get();
                $question7b3 = VWFinancialPolicy::select(DB::raw('fin_eva_a_question7b3, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b3')->get();
                $fin_eva_a_comment7b3 = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment7b3, count(fin_eva_a_comment7b3)'))->groupBy('fin_eva_a_comment7b3')->get();
                $question7c = VWFinancialPolicy::select(DB::raw('fin_eva_a_question7c, count(financial_id) AS y'))->groupBy('fin_eva_a_question7c')->get();
                $fin_eva_a_comment7c = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment7c, count(fin_eva_a_comment7c)'))->groupBy('fin_eva_a_comment7c')->get();
                $question7d = VWFinancialPolicy::select(DB::raw('fin_eva_a_question7d, count(financial_id) AS y'))->groupBy('fin_eva_a_question7d')->get();
                $fin_eva_a_comment7d = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment7d, count(fin_eva_a_comment7d)'))->groupBy('fin_eva_a_comment7d')->get();
                $fin_eva_a_comment8a = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment8a, count(fin_eva_a_comment8a)'))->groupBy('fin_eva_a_comment8a')->get();
                $fin_eva_a_comment8b = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment8b, count(fin_eva_a_comment8b)'))->groupBy('fin_eva_a_comment8b')->get();
                $question8c = VWFinancialPolicy::select(DB::raw('fin_eva_a_question8c, count(financial_id) AS y'))->groupBy('fin_eva_a_question8c')->get();
                $fin_eva_a_comment8c = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment8c, count(fin_eva_a_comment8c)'))->groupBy('fin_eva_a_comment8c')->get();
                $question8d = VWFinancialPolicy::select(DB::raw('fin_eva_a_question8d, count(financial_id) AS y'))->groupBy('fin_eva_a_question8d')->get();
                $fin_eva_a_comment8d = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment8d, count(fin_eva_a_comment8d)'))->groupBy('fin_eva_a_comment8d')->get();
                $fin_eva_a_comment8e = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment8e, count(fin_eva_a_comment8e)'))->groupBy('fin_eva_a_comment8e')->get();
                $fin_eva_a_comment8f = VWFinancialPolicy::select(DB::raw('fin_eva_a_comment8f, count(fin_eva_a_comment8f)'))->groupBy('fin_eva_a_comment8f')->get();

                break;
        
            case 'Area':
                $total = VWFinancialPolicy::where('area', $area)->count();
                $area_area = VWFinancialPolicy::where('area', $area)->select(DB::raw('area, count(area)'))->groupBy('area')->get();
                $district_dist = VWFinancialPolicy::where('area', $area)->select(DB::raw('district, count(district)'))->groupBy('district')->get();
                $local_loc = VWFinancialPolicy::where('area', $area)->select(DB::raw('local, count(local)'))->groupBy('local')->get();
                $question1a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question1a, count(financial_id) AS y'))->groupBy('fin_eva_a_question1a')->get();
                $fin_eva_a_comment1a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment1a, count(fin_eva_a_comment1a)'))->groupBy('fin_eva_a_comment1a')->get();
                $question1b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question1b, count(financial_id) AS y'))->groupBy('fin_eva_a_question1b')->get();
                $fin_eva_a_comment1b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment1b, count(fin_eva_a_comment1b)'))->groupBy('fin_eva_a_comment1b')->get();
                $question1c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question1c, count(financial_id) AS y'))->groupBy('fin_eva_a_question1c')->get();
                $fin_eva_a_comment1c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment1c, count(fin_eva_a_comment1c)'))->groupBy('fin_eva_a_comment1c')->get();
                $question1d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question1d, count(financial_id) AS y'))->groupBy('fin_eva_a_question1d')->get();
                $fin_eva_a_comment1d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment1d, count(fin_eva_a_comment1d)'))->groupBy('fin_eva_a_comment1d')->get();
                $question1e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question1e, count(financial_id) AS y'))->groupBy('fin_eva_a_question1e')->get();
                $fin_eva_a_comment1e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment1e, count(fin_eva_a_comment1e)'))->groupBy('fin_eva_a_comment1e')->get();
                $question1f = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question1f, count(financial_id) AS y'))->groupBy('fin_eva_a_question1f')->get();
                $fin_eva_a_comment1f = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment1f, count(fin_eva_a_comment1f)'))->groupBy('fin_eva_a_comment1f')->get();
                $question1g = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question1g, count(financial_id) AS y'))->groupBy('fin_eva_a_question1g')->get();
                $fin_eva_a_comment1g = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment1g, count(fin_eva_a_comment1g)'))->groupBy('fin_eva_a_comment1g')->get();
                $question2a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question2a, count(financial_id) AS y'))->groupBy('fin_eva_a_question2a')->get();
                $fin_eva_a_comment2a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment2a, count(fin_eva_a_comment2a)'))->groupBy('fin_eva_a_comment2a')->get();
                $question2b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question2b, count(financial_id) AS y'))->groupBy('fin_eva_a_question2b')->get();
                $fin_eva_a_comment2b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment2b, count(fin_eva_a_comment2b)'))->groupBy('fin_eva_a_comment2b')->get();
                $question2c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question2c, count(financial_id) AS y'))->groupBy('fin_eva_a_question2c')->get();
                $fin_eva_a_comment2c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment2c, count(fin_eva_a_comment2c)'))->groupBy('fin_eva_a_comment2c')->get();
                $question3a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3a, count(financial_id) AS y'))->groupBy('fin_eva_a_question3a')->get();
                $fin_eva_a_comment3a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3a, count(fin_eva_a_comment3a)'))->groupBy('fin_eva_a_comment3a')->get();
                $question3b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3b, count(financial_id) AS y'))->groupBy('fin_eva_a_question3b')->get();
                $fin_eva_a_comment3b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3b, count(fin_eva_a_comment3b)'))->groupBy('fin_eva_a_comment3b')->get();
                $question3c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3c, count(financial_id) AS y'))->groupBy('fin_eva_a_question3c')->get();
                $fin_eva_a_comment3c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3c, count(fin_eva_a_comment3c)'))->groupBy('fin_eva_a_comment3c')->get();
                $question3d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3d, count(financial_id) AS y'))->groupBy('fin_eva_a_question3d')->get();
                $fin_eva_a_comment3d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3d, count(fin_eva_a_comment3d)'))->groupBy('fin_eva_a_comment3d')->get();
                $question3e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3e, count(financial_id) AS y'))->groupBy('fin_eva_a_question3e')->get();
                $fin_eva_a_comment3e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3e, count(fin_eva_a_comment3e)'))->groupBy('fin_eva_a_comment3e')->get();
                $question3f = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3f, count(financial_id) AS y'))->groupBy('fin_eva_a_question3f')->get();
                $fin_eva_a_comment3f = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3f, count(fin_eva_a_comment3f)'))->groupBy('fin_eva_a_comment3f')->get();
                $question3g = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3g, count(financial_id) AS y'))->groupBy('fin_eva_a_question3g')->get();
                $fin_eva_a_comment3g = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3g, count(fin_eva_a_comment3g)'))->groupBy('fin_eva_a_comment3g')->get();
                $question3h = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3h, count(financial_id) AS y'))->groupBy('fin_eva_a_question3h')->get();
                $fin_eva_a_comment3h = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3h, count(fin_eva_a_comment3h)'))->groupBy('fin_eva_a_comment3h')->get();
                $question3i = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question3i, count(financial_id) AS y'))->groupBy('fin_eva_a_question3i')->get();
                $fin_eva_a_comment3i = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment3i, count(fin_eva_a_comment3i)'))->groupBy('fin_eva_a_comment3i')->get();
                $question4a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question4a, count(financial_id) AS y'))->groupBy('fin_eva_a_question4a')->get();
                $fin_eva_a_comment4a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4a, count(fin_eva_a_comment4a)'))->groupBy('fin_eva_a_comment4a')->get();
                $fin_eva_a_comment4b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4b, count(fin_eva_a_comment4b)'))->groupBy('fin_eva_a_comment4b')->get();
                $fin_eva_a_comment4c1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4c1, count(fin_eva_a_comment4c1)'))->groupBy('fin_eva_a_comment4c1')->get();
                $fin_eva_a_comment4c2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4c2, count(fin_eva_a_comment4c2)'))->groupBy('fin_eva_a_comment4c2')->get();
                $fin_eva_a_comment4c3 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4c3, count(fin_eva_a_comment4c3)'))->groupBy('fin_eva_a_comment4c3')->get();
                $fin_eva_a_comment4d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4d, count(fin_eva_a_comment4d)'))->groupBy('fin_eva_a_comment4d')->get();
                $fin_eva_a_comment4e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4e, count(fin_eva_a_comment4e)'))->groupBy('fin_eva_a_comment4e')->get();
                $fin_eva_a_comment4f = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment4f, count(fin_eva_a_comment4f)'))->groupBy('fin_eva_a_comment4f')->get();
                $fin_eva_a_comment5a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment5a, count(fin_eva_a_comment5a)'))->groupBy('fin_eva_a_comment5a')->get();
                $fin_eva_a_comment5b1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment5b1, count(fin_eva_a_comment5b1)'))->groupBy('fin_eva_a_comment5b1')->get();
                $fin_eva_a_comment5b2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment5b2, count(fin_eva_a_comment5b2)'))->groupBy('fin_eva_a_comment5b2')->get();
                $fin_eva_a_comment5b3 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment5b3, count(fin_eva_a_comment5b3)'))->groupBy('fin_eva_a_comment5b3')->get();
                $fin_eva_a_comment5b4 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment5b4, count(fin_eva_a_comment5b4)'))->groupBy('fin_eva_a_comment5b4')->get();
                $fin_eva_a_comment5c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment5c, count(fin_eva_a_comment5c)'))->groupBy('fin_eva_a_comment5c')->get();
                $question6a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question6a, count(financial_id) AS y'))->groupBy('fin_eva_a_question6a')->get();
                $fin_eva_a_comment6a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment6a, count(fin_eva_a_comment6a)'))->groupBy('fin_eva_a_comment6a')->get();
                $fin_eva_a_comment6b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment6b, count(fin_eva_a_comment6b)'))->groupBy('fin_eva_a_comment6b')->get();
                $question6c1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question6c1, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c1')->get();
                $fin_eva_a_comment6c1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment6c1, count(fin_eva_a_comment6c1)'))->groupBy('fin_eva_a_comment6c1')->get();
                $question6c2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question6c2, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c2')->get();
                $fin_eva_a_comment6c2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment6c2, count(fin_eva_a_comment6c2)'))->groupBy('fin_eva_a_comment6c2')->get();
                $fin_eva_a_comment6c3 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment6c3, count(fin_eva_a_comment6c3)'))->groupBy('fin_eva_a_comment6c3')->get();
                $question6d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question6d, count(financial_id) AS y'))->groupBy('fin_eva_a_question6d')->get();
                $fin_eva_a_comment6d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment6d, count(fin_eva_a_comment6d)'))->groupBy('fin_eva_a_comment6d')->get();
                $question6e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question6e, count(financial_id) AS y'))->groupBy('fin_eva_a_question6e')->get();
                $fin_eva_a_comment6e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment6e, count(fin_eva_a_comment6e)'))->groupBy('fin_eva_a_comment6e')->get();
                $question7a1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question7a1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a1')->get();
                $fin_eva_a_comment7a1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment7a1, count(fin_eva_a_comment7a1)'))->groupBy('fin_eva_a_comment7a1')->get();
                $question7a2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question7a2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a2')->get();
                $fin_eva_a_comment7a2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment7a2, count(fin_eva_a_comment7a2)'))->groupBy('fin_eva_a_comment7a2')->get();
                $question7b1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question7b1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b1')->get();
                $fin_eva_a_comment7b1 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment7b1, count(fin_eva_a_comment7b1)'))->groupBy('fin_eva_a_comment7b1')->get();
                $question7b2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question7b2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b2')->get();
                $fin_eva_a_comment7b2 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment7b2, count(fin_eva_a_comment7b2)'))->groupBy('fin_eva_a_comment7b2')->get();
                $question7b3 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question7b3, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b3')->get();
                $fin_eva_a_comment7b3 = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment7b3, count(fin_eva_a_comment7b3)'))->groupBy('fin_eva_a_comment7b3')->get();
                $question7c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question7c, count(financial_id) AS y'))->groupBy('fin_eva_a_question7c')->get();
                $fin_eva_a_comment7c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment7c, count(fin_eva_a_comment7c)'))->groupBy('fin_eva_a_comment7c')->get();
                $question7d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question7d, count(financial_id) AS y'))->groupBy('fin_eva_a_question7d')->get();
                $fin_eva_a_comment7d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment7d, count(fin_eva_a_comment7d)'))->groupBy('fin_eva_a_comment7d')->get();
                $fin_eva_a_comment8a = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment8a, count(fin_eva_a_comment8a)'))->groupBy('fin_eva_a_comment8a')->get();
                $fin_eva_a_comment8b = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment8b, count(fin_eva_a_comment8b)'))->groupBy('fin_eva_a_comment8b')->get();
                $question8c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question8c, count(financial_id) AS y'))->groupBy('fin_eva_a_question8c')->get();
                $fin_eva_a_comment8c = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment8c, count(fin_eva_a_comment8c)'))->groupBy('fin_eva_a_comment8c')->get();
                $question8d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_question8d, count(financial_id) AS y'))->groupBy('fin_eva_a_question8d')->get();
                $fin_eva_a_comment8d = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment8d, count(fin_eva_a_comment8d)'))->groupBy('fin_eva_a_comment8d')->get();
                $fin_eva_a_comment8e = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment8e, count(fin_eva_a_comment8e)'))->groupBy('fin_eva_a_comment8e')->get();
                $fin_eva_a_comment8f = VWFinancialPolicy::where('area', $area)->select(DB::raw('fin_eva_a_comment8f, count(fin_eva_a_comment8f)'))->groupBy('fin_eva_a_comment8f')->get();
                
                break;
        
            case 'District':
                $total = VWFinancialPolicy::where('area', $area)->where('district', $dist)->count();
                $area_area = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('area, count(area)'))->groupBy('area')->get();
                $district_dist = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('district, count(district)'))->groupBy('district')->get();
                $local_loc = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('local, count(local)'))->groupBy('local')->get();
                $question1a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question1a, count(financial_id) AS y'))->groupBy('fin_eva_a_question1a')->get();
                $fin_eva_a_comment1a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment1a, count(fin_eva_a_comment1a)'))->groupBy('fin_eva_a_comment1a')->get();
                $question1b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question1b, count(financial_id) AS y'))->groupBy('fin_eva_a_question1b')->get();
                $fin_eva_a_comment1b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment1b, count(fin_eva_a_comment1b)'))->groupBy('fin_eva_a_comment1b')->get();
                $question1c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question1c, count(financial_id) AS y'))->groupBy('fin_eva_a_question1c')->get();
                $fin_eva_a_comment1c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment1c, count(fin_eva_a_comment1c)'))->groupBy('fin_eva_a_comment1c')->get();
                $question1d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question1d, count(financial_id) AS y'))->groupBy('fin_eva_a_question1d')->get();
                $fin_eva_a_comment1d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment1d, count(fin_eva_a_comment1d)'))->groupBy('fin_eva_a_comment1d')->get();
                $question1e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question1e, count(financial_id) AS y'))->groupBy('fin_eva_a_question1e')->get();
                $fin_eva_a_comment1e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment1e, count(fin_eva_a_comment1e)'))->groupBy('fin_eva_a_comment1e')->get();
                $question1f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question1f, count(financial_id) AS y'))->groupBy('fin_eva_a_question1f')->get();
                $fin_eva_a_comment1f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment1f, count(fin_eva_a_comment1f)'))->groupBy('fin_eva_a_comment1f')->get();
                $question1g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question1g, count(financial_id) AS y'))->groupBy('fin_eva_a_question1g')->get();
                $fin_eva_a_comment1g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment1g, count(fin_eva_a_comment1g)'))->groupBy('fin_eva_a_comment1g')->get();
                $question2a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question2a, count(financial_id) AS y'))->groupBy('fin_eva_a_question2a')->get();
                $fin_eva_a_comment2a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment2a, count(fin_eva_a_comment2a)'))->groupBy('fin_eva_a_comment2a')->get();
                $question2b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question2b, count(financial_id) AS y'))->groupBy('fin_eva_a_question2b')->get();
                $fin_eva_a_comment2b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment2b, count(fin_eva_a_comment2b)'))->groupBy('fin_eva_a_comment2b')->get();
                $question2c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question2c, count(financial_id) AS y'))->groupBy('fin_eva_a_question2c')->get();
                $fin_eva_a_comment2c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment2c, count(fin_eva_a_comment2c)'))->groupBy('fin_eva_a_comment2c')->get();
                $question3a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3a, count(financial_id) AS y'))->groupBy('fin_eva_a_question3a')->get();
                $fin_eva_a_comment3a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3a, count(fin_eva_a_comment3a)'))->groupBy('fin_eva_a_comment3a')->get();
                $question3b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3b, count(financial_id) AS y'))->groupBy('fin_eva_a_question3b')->get();
                $fin_eva_a_comment3b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3b, count(fin_eva_a_comment3b)'))->groupBy('fin_eva_a_comment3b')->get();
                $question3c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3c, count(financial_id) AS y'))->groupBy('fin_eva_a_question3c')->get();
                $fin_eva_a_comment3c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3c, count(fin_eva_a_comment3c)'))->groupBy('fin_eva_a_comment3c')->get();
                $question3d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3d, count(financial_id) AS y'))->groupBy('fin_eva_a_question3d')->get();
                $fin_eva_a_comment3d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3d, count(fin_eva_a_comment3d)'))->groupBy('fin_eva_a_comment3d')->get();
                $question3e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3e, count(financial_id) AS y'))->groupBy('fin_eva_a_question3e')->get();
                $fin_eva_a_comment3e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3e, count(fin_eva_a_comment3e)'))->groupBy('fin_eva_a_comment3e')->get();
                $question3f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3f, count(financial_id) AS y'))->groupBy('fin_eva_a_question3f')->get();
                $fin_eva_a_comment3f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3f, count(fin_eva_a_comment3f)'))->groupBy('fin_eva_a_comment3f')->get();
                $question3g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3g, count(financial_id) AS y'))->groupBy('fin_eva_a_question3g')->get();
                $fin_eva_a_comment3g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3g, count(fin_eva_a_comment3g)'))->groupBy('fin_eva_a_comment3g')->get();
                $question3h = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3h, count(financial_id) AS y'))->groupBy('fin_eva_a_question3h')->get();
                $fin_eva_a_comment3h = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3h, count(fin_eva_a_comment3h)'))->groupBy('fin_eva_a_comment3h')->get();
                $question3i = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question3i, count(financial_id) AS y'))->groupBy('fin_eva_a_question3i')->get();
                $fin_eva_a_comment3i = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment3i, count(fin_eva_a_comment3i)'))->groupBy('fin_eva_a_comment3i')->get();
                $question4a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question4a, count(financial_id) AS y'))->groupBy('fin_eva_a_question4a')->get();
                $fin_eva_a_comment4a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4a, count(fin_eva_a_comment4a)'))->groupBy('fin_eva_a_comment4a')->get();
                $fin_eva_a_comment4b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4b, count(fin_eva_a_comment4b)'))->groupBy('fin_eva_a_comment4b')->get();
                $fin_eva_a_comment4c1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4c1, count(fin_eva_a_comment4c1)'))->groupBy('fin_eva_a_comment4c1')->get();
                $fin_eva_a_comment4c2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4c2, count(fin_eva_a_comment4c2)'))->groupBy('fin_eva_a_comment4c2')->get();
                $fin_eva_a_comment4c3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4c3, count(fin_eva_a_comment4c3)'))->groupBy('fin_eva_a_comment4c3')->get();
                $fin_eva_a_comment4d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4d, count(fin_eva_a_comment4d)'))->groupBy('fin_eva_a_comment4d')->get();
                $fin_eva_a_comment4e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4e, count(fin_eva_a_comment4e)'))->groupBy('fin_eva_a_comment4e')->get();
                $fin_eva_a_comment4f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment4f, count(fin_eva_a_comment4f)'))->groupBy('fin_eva_a_comment4f')->get();
                $fin_eva_a_comment5a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment5a, count(fin_eva_a_comment5a)'))->groupBy('fin_eva_a_comment5a')->get();
                $fin_eva_a_comment5b1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment5b1, count(fin_eva_a_comment5b1)'))->groupBy('fin_eva_a_comment5b1')->get();
                $fin_eva_a_comment5b2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment5b2, count(fin_eva_a_comment5b2)'))->groupBy('fin_eva_a_comment5b2')->get();
                $fin_eva_a_comment5b3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment5b3, count(fin_eva_a_comment5b3)'))->groupBy('fin_eva_a_comment5b3')->get();
                $fin_eva_a_comment5b4 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment5b4, count(fin_eva_a_comment5b4)'))->groupBy('fin_eva_a_comment5b4')->get();
                $fin_eva_a_comment5c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment5c, count(fin_eva_a_comment5c)'))->groupBy('fin_eva_a_comment5c')->get();
                $question6a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question6a, count(financial_id) AS y'))->groupBy('fin_eva_a_question6a')->get();
                $fin_eva_a_comment6a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment6a, count(fin_eva_a_comment6a)'))->groupBy('fin_eva_a_comment6a')->get();
                $fin_eva_a_comment6b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment6b, count(fin_eva_a_comment6b)'))->groupBy('fin_eva_a_comment6b')->get();
                $question6c1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question6c1, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c1')->get();
                $fin_eva_a_comment6c1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment6c1, count(fin_eva_a_comment6c1)'))->groupBy('fin_eva_a_comment6c1')->get();
                $question6c2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question6c2, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c2')->get();
                $fin_eva_a_comment6c2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment6c2, count(fin_eva_a_comment6c2)'))->groupBy('fin_eva_a_comment6c2')->get();
                $fin_eva_a_comment6c3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment6c3, count(fin_eva_a_comment6c3)'))->groupBy('fin_eva_a_comment6c3')->get();
                $question6d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question6d, count(financial_id) AS y'))->groupBy('fin_eva_a_question6d')->get();
                $fin_eva_a_comment6d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment6d, count(fin_eva_a_comment6d)'))->groupBy('fin_eva_a_comment6d')->get();
                $question6e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question6e, count(financial_id) AS y'))->groupBy('fin_eva_a_question6e')->get();
                $fin_eva_a_comment6e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment6e, count(fin_eva_a_comment6e)'))->groupBy('fin_eva_a_comment6e')->get();
                $question7a1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question7a1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a1')->get();
                $fin_eva_a_comment7a1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment7a1, count(fin_eva_a_comment7a1)'))->groupBy('fin_eva_a_comment7a1')->get();
                $question7a2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question7a2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a2')->get();
                $fin_eva_a_comment7a2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment7a2, count(fin_eva_a_comment7a2)'))->groupBy('fin_eva_a_comment7a2')->get();
                $question7b1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question7b1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b1')->get();
                $fin_eva_a_comment7b1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment7b1, count(fin_eva_a_comment7b1)'))->groupBy('fin_eva_a_comment7b1')->get();
                $question7b2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question7b2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b2')->get();
                $fin_eva_a_comment7b2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment7b2, count(fin_eva_a_comment7b2)'))->groupBy('fin_eva_a_comment7b2')->get();
                $question7b3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question7b3, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b3')->get();
                $fin_eva_a_comment7b3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment7b3, count(fin_eva_a_comment7b3)'))->groupBy('fin_eva_a_comment7b3')->get();
                $question7c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question7c, count(financial_id) AS y'))->groupBy('fin_eva_a_question7c')->get();
                $fin_eva_a_comment7c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment7c, count(fin_eva_a_comment7c)'))->groupBy('fin_eva_a_comment7c')->get();
                $question7d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question7d, count(financial_id) AS y'))->groupBy('fin_eva_a_question7d')->get();
                $fin_eva_a_comment7d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment7d, count(fin_eva_a_comment7d)'))->groupBy('fin_eva_a_comment7d')->get();
                $fin_eva_a_comment8a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment8a, count(fin_eva_a_comment8a)'))->groupBy('fin_eva_a_comment8a')->get();
                $fin_eva_a_comment8b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment8b, count(fin_eva_a_comment8b)'))->groupBy('fin_eva_a_comment8b')->get();
                $question8c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question8c, count(financial_id) AS y'))->groupBy('fin_eva_a_question8c')->get();
                $fin_eva_a_comment8c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment8c, count(fin_eva_a_comment8c)'))->groupBy('fin_eva_a_comment8c')->get();
                $question8d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_question8d, count(financial_id) AS y'))->groupBy('fin_eva_a_question8d')->get();
                $fin_eva_a_comment8d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment8d, count(fin_eva_a_comment8d)'))->groupBy('fin_eva_a_comment8d')->get();
                $fin_eva_a_comment8e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment8e, count(fin_eva_a_comment8e)'))->groupBy('fin_eva_a_comment8e')->get();
                $fin_eva_a_comment8f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->select(DB::raw('fin_eva_a_comment8f, count(fin_eva_a_comment8f)'))->groupBy('fin_eva_a_comment8f')->get();
                
                break;
        
            case 'Local':
                $total = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->count();
                $area_area = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('area, count(area)'))->groupBy('area')->get();
                $district_dist = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('district, count(district)'))->groupBy('district')->get();
                $local_loc = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('local, count(local)'))->groupBy('local')->get();
                $question1a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question1a, count(financial_id) AS y'))->groupBy('fin_eva_a_question1a')->get();
                $fin_eva_a_comment1a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment1a, count(fin_eva_a_comment1a)'))->groupBy('fin_eva_a_comment1a')->get();
                $question1b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question1b, count(financial_id) AS y'))->groupBy('fin_eva_a_question1b')->get();
                $fin_eva_a_comment1b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment1b, count(fin_eva_a_comment1b)'))->groupBy('fin_eva_a_comment1b')->get();
                $question1c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question1c, count(financial_id) AS y'))->groupBy('fin_eva_a_question1c')->get();
                $fin_eva_a_comment1c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment1c, count(fin_eva_a_comment1c)'))->groupBy('fin_eva_a_comment1c')->get();
                $question1d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question1d, count(financial_id) AS y'))->groupBy('fin_eva_a_question1d')->get();
                $fin_eva_a_comment1d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment1d, count(fin_eva_a_comment1d)'))->groupBy('fin_eva_a_comment1d')->get();
                $question1e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question1e, count(financial_id) AS y'))->groupBy('fin_eva_a_question1e')->get();
                $fin_eva_a_comment1e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment1e, count(fin_eva_a_comment1e)'))->groupBy('fin_eva_a_comment1e')->get();
                $question1f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question1f, count(financial_id) AS y'))->groupBy('fin_eva_a_question1f')->get();
                $fin_eva_a_comment1f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment1f, count(fin_eva_a_comment1f)'))->groupBy('fin_eva_a_comment1f')->get();
                $question1g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question1g, count(financial_id) AS y'))->groupBy('fin_eva_a_question1g')->get();
                $fin_eva_a_comment1g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment1g, count(fin_eva_a_comment1g)'))->groupBy('fin_eva_a_comment1g')->get();
                $question2a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question2a, count(financial_id) AS y'))->groupBy('fin_eva_a_question2a')->get();
                $fin_eva_a_comment2a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment2a, count(fin_eva_a_comment2a)'))->groupBy('fin_eva_a_comment2a')->get();
                $question2b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question2b, count(financial_id) AS y'))->groupBy('fin_eva_a_question2b')->get();
                $fin_eva_a_comment2b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment2b, count(fin_eva_a_comment2b)'))->groupBy('fin_eva_a_comment2b')->get();
                $question2c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question2c, count(financial_id) AS y'))->groupBy('fin_eva_a_question2c')->get();
                $fin_eva_a_comment2c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment2c, count(fin_eva_a_comment2c)'))->groupBy('fin_eva_a_comment2c')->get();
                $question3a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3a, count(financial_id) AS y'))->groupBy('fin_eva_a_question3a')->get();
                $fin_eva_a_comment3a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3a, count(fin_eva_a_comment3a)'))->groupBy('fin_eva_a_comment3a')->get();
                $question3b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3b, count(financial_id) AS y'))->groupBy('fin_eva_a_question3b')->get();
                $fin_eva_a_comment3b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3b, count(fin_eva_a_comment3b)'))->groupBy('fin_eva_a_comment3b')->get();
                $question3c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3c, count(financial_id) AS y'))->groupBy('fin_eva_a_question3c')->get();
                $fin_eva_a_comment3c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3c, count(fin_eva_a_comment3c)'))->groupBy('fin_eva_a_comment3c')->get();
                $question3d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3d, count(financial_id) AS y'))->groupBy('fin_eva_a_question3d')->get();
                $fin_eva_a_comment3d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3d, count(fin_eva_a_comment3d)'))->groupBy('fin_eva_a_comment3d')->get();
                $question3e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3e, count(financial_id) AS y'))->groupBy('fin_eva_a_question3e')->get();
                $fin_eva_a_comment3e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3e, count(fin_eva_a_comment3e)'))->groupBy('fin_eva_a_comment3e')->get();
                $question3f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3f, count(financial_id) AS y'))->groupBy('fin_eva_a_question3f')->get();
                $fin_eva_a_comment3f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3f, count(fin_eva_a_comment3f)'))->groupBy('fin_eva_a_comment3f')->get();
                $question3g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3g, count(financial_id) AS y'))->groupBy('fin_eva_a_question3g')->get();
                $fin_eva_a_comment3g = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3g, count(fin_eva_a_comment3g)'))->groupBy('fin_eva_a_comment3g')->get();
                $question3h = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3h, count(financial_id) AS y'))->groupBy('fin_eva_a_question3h')->get();
                $fin_eva_a_comment3h = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3h, count(fin_eva_a_comment3h)'))->groupBy('fin_eva_a_comment3h')->get();
                $question3i = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question3i, count(financial_id) AS y'))->groupBy('fin_eva_a_question3i')->get();
                $fin_eva_a_comment3i = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment3i, count(fin_eva_a_comment3i)'))->groupBy('fin_eva_a_comment3i')->get();
                $question4a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question4a, count(financial_id) AS y'))->groupBy('fin_eva_a_question4a')->get();
                $fin_eva_a_comment4a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4a, count(fin_eva_a_comment4a)'))->groupBy('fin_eva_a_comment4a')->get();
                $fin_eva_a_comment4b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4b, count(fin_eva_a_comment4b)'))->groupBy('fin_eva_a_comment4b')->get();
                $fin_eva_a_comment4c1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4c1, count(fin_eva_a_comment4c1)'))->groupBy('fin_eva_a_comment4c1')->get();
                $fin_eva_a_comment4c2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4c2, count(fin_eva_a_comment4c2)'))->groupBy('fin_eva_a_comment4c2')->get();
                $fin_eva_a_comment4c3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4c3, count(fin_eva_a_comment4c3)'))->groupBy('fin_eva_a_comment4c3')->get();
                $fin_eva_a_comment4d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4d, count(fin_eva_a_comment4d)'))->groupBy('fin_eva_a_comment4d')->get();
                $fin_eva_a_comment4e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4e, count(fin_eva_a_comment4e)'))->groupBy('fin_eva_a_comment4e')->get();
                $fin_eva_a_comment4f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment4f, count(fin_eva_a_comment4f)'))->groupBy('fin_eva_a_comment4f')->get();
                $fin_eva_a_comment5a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment5a, count(fin_eva_a_comment5a)'))->groupBy('fin_eva_a_comment5a')->get();
                $fin_eva_a_comment5b1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment5b1, count(fin_eva_a_comment5b1)'))->groupBy('fin_eva_a_comment5b1')->get();
                $fin_eva_a_comment5b2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment5b2, count(fin_eva_a_comment5b2)'))->groupBy('fin_eva_a_comment5b2')->get();
                $fin_eva_a_comment5b3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment5b3, count(fin_eva_a_comment5b3)'))->groupBy('fin_eva_a_comment5b3')->get();
                $fin_eva_a_comment5b4 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment5b4, count(fin_eva_a_comment5b4)'))->groupBy('fin_eva_a_comment5b4')->get();
                $fin_eva_a_comment5c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment5c, count(fin_eva_a_comment5c)'))->groupBy('fin_eva_a_comment5c')->get();
                $question6a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question6a, count(financial_id) AS y'))->groupBy('fin_eva_a_question6a')->get();
                $fin_eva_a_comment6a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment6a, count(fin_eva_a_comment6a)'))->groupBy('fin_eva_a_comment6a')->get();
                $fin_eva_a_comment6b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment6b, count(fin_eva_a_comment6b)'))->groupBy('fin_eva_a_comment6b')->get();
                $question6c1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question6c1, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c1')->get();
                $fin_eva_a_comment6c1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment6c1, count(fin_eva_a_comment6c1)'))->groupBy('fin_eva_a_comment6c1')->get();
                $question6c2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question6c2, count(financial_id) AS y'))->groupBy('fin_eva_a_question6c2')->get();
                $fin_eva_a_comment6c2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment6c2, count(fin_eva_a_comment6c2)'))->groupBy('fin_eva_a_comment6c2')->get();
                $fin_eva_a_comment6c3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment6c3, count(fin_eva_a_comment6c3)'))->groupBy('fin_eva_a_comment6c3')->get();
                $question6d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question6d, count(financial_id) AS y'))->groupBy('fin_eva_a_question6d')->get();
                $fin_eva_a_comment6d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment6d, count(fin_eva_a_comment6d)'))->groupBy('fin_eva_a_comment6d')->get();
                $question6e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question6e, count(financial_id) AS y'))->groupBy('fin_eva_a_question6e')->get();
                $fin_eva_a_comment6e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment6e, count(fin_eva_a_comment6e)'))->groupBy('fin_eva_a_comment6e')->get();
                $question7a1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question7a1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a1')->get();
                $fin_eva_a_comment7a1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment7a1, count(fin_eva_a_comment7a1)'))->groupBy('fin_eva_a_comment7a1')->get();
                $question7a2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question7a2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7a2')->get();
                $fin_eva_a_comment7a2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment7a2, count(fin_eva_a_comment7a2)'))->groupBy('fin_eva_a_comment7a2')->get();
                $question7b1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question7b1, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b1')->get();
                $fin_eva_a_comment7b1 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment7b1, count(fin_eva_a_comment7b1)'))->groupBy('fin_eva_a_comment7b1')->get();
                $question7b2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question7b2, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b2')->get();
                $fin_eva_a_comment7b2 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment7b2, count(fin_eva_a_comment7b2)'))->groupBy('fin_eva_a_comment7b2')->get();
                $question7b3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question7b3, count(financial_id) AS y'))->groupBy('fin_eva_a_question7b3')->get();
                $fin_eva_a_comment7b3 = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment7b3, count(fin_eva_a_comment7b3)'))->groupBy('fin_eva_a_comment7b3')->get();
                $question7c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question7c, count(financial_id) AS y'))->groupBy('fin_eva_a_question7c')->get();
                $fin_eva_a_comment7c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment7c, count(fin_eva_a_comment7c)'))->groupBy('fin_eva_a_comment7c')->get();
                $question7d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question7d, count(financial_id) AS y'))->groupBy('fin_eva_a_question7d')->get();
                $fin_eva_a_comment7d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment7d, count(fin_eva_a_comment7d)'))->groupBy('fin_eva_a_comment7d')->get();
                $fin_eva_a_comment8a = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment8a, count(fin_eva_a_comment8a)'))->groupBy('fin_eva_a_comment8a')->get();
                $fin_eva_a_comment8b = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment8b, count(fin_eva_a_comment8b)'))->groupBy('fin_eva_a_comment8b')->get();
                $question8c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question8c, count(financial_id) AS y'))->groupBy('fin_eva_a_question8c')->get();
                $fin_eva_a_comment8c = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment8c, count(fin_eva_a_comment8c)'))->groupBy('fin_eva_a_comment8c')->get();
                $question8d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_question8d, count(financial_id) AS y'))->groupBy('fin_eva_a_question8d')->get();
                $fin_eva_a_comment8d = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment8d, count(fin_eva_a_comment8d)'))->groupBy('fin_eva_a_comment8d')->get();
                $fin_eva_a_comment8e = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment8e, count(fin_eva_a_comment8e)'))->groupBy('fin_eva_a_comment8e')->get();
                $fin_eva_a_comment8f = VWFinancialPolicy::where('area', $area)->where('district', $dist)->where('local', $loc)->select(DB::raw('fin_eva_a_comment8f, count(fin_eva_a_comment8f)'))->groupBy('fin_eva_a_comment8f')->get();
               
                break;
            
            default:
                return Session::flash('error', 'Wrong Input');
                break;
        }

        return [
            'total' => $total,
            'area' => $area_area,
            'district' => $district_dist,
            'local' => $local_loc,
            'question1a' => $question1a,
            'fin_eva_a_comment1a' => $fin_eva_a_comment1a,
            'question1b' => $question1b,
            'fin_eva_a_comment1b' => $fin_eva_a_comment1b,
            'question1c' => $question1c,
            'fin_eva_a_comment1c' => $fin_eva_a_comment1c,
            'question1d' => $question1d,
            'fin_eva_a_comment1d' => $fin_eva_a_comment1d,
            'question1e' => $question1e,
            'fin_eva_a_comment1e' => $fin_eva_a_comment1e,
            'question1f' => $question1f,
            'fin_eva_a_comment1f' => $fin_eva_a_comment1f,
            'question1g' => $question1g,
            'fin_eva_a_comment1g' => $fin_eva_a_comment1g,
            'question2a' => $question2a,
            'fin_eva_a_comment2a' => $fin_eva_a_comment2a,
            'question2b' => $question2b,
            'fin_eva_a_comment2b' => $fin_eva_a_comment2b,
            'question2c' => $question2c,
            'fin_eva_a_comment2c' => $fin_eva_a_comment2c,
            'question3a' => $question3a,
            'fin_eva_a_comment3a' => $fin_eva_a_comment3a,
            'question3b' => $question3b,
            'fin_eva_a_comment3b' => $fin_eva_a_comment3b,
            'question3c' => $question3c,
            'fin_eva_a_comment3c' => $fin_eva_a_comment3c,
            'question3d' => $question3d,
            'fin_eva_a_comment3d' => $fin_eva_a_comment3d,
            'question3e' => $question3e,
            'fin_eva_a_comment3e' => $fin_eva_a_comment3e,
            'question3f' => $question3f,
            'fin_eva_a_comment3f' => $fin_eva_a_comment3f,
            'question3g' => $question3g,
            'fin_eva_a_comment3g' => $fin_eva_a_comment3g,
            'question3h' => $question3h,
            'fin_eva_a_comment3h' => $fin_eva_a_comment3h,
            'question3i' => $question3i,
            'fin_eva_a_comment3i' => $fin_eva_a_comment3i,
            'question4a' => $question4a,
            'fin_eva_a_comment4a' => $fin_eva_a_comment4a,
            'fin_eva_a_comment4b' => $fin_eva_a_comment4b,
            'fin_eva_a_comment4c1' => $fin_eva_a_comment4c1,
            'fin_eva_a_comment4c2' => $fin_eva_a_comment4c2,
            'fin_eva_a_comment4c3' => $fin_eva_a_comment4c3,
            'fin_eva_a_comment4d' => $fin_eva_a_comment4d,
            'fin_eva_a_comment4e' => $fin_eva_a_comment4e,
            'fin_eva_a_comment4f' => $fin_eva_a_comment4f,
            'fin_eva_a_comment5a' => $fin_eva_a_comment5a,
            'fin_eva_a_comment5b1' => $fin_eva_a_comment5b1,
            'fin_eva_a_comment5b2' => $fin_eva_a_comment5b2,
            'fin_eva_a_comment5b3' => $fin_eva_a_comment5b3,
            'fin_eva_a_comment5b4' => $fin_eva_a_comment5b4,
            'fin_eva_a_comment5c' => $fin_eva_a_comment5c,
            'question6a' => $question6a,
            'fin_eva_a_comment6a' => $fin_eva_a_comment6a,
            'fin_eva_a_comment6b' => $fin_eva_a_comment6b,
            'question6c1' => $question6c1,
            'fin_eva_a_comment6c1' => $fin_eva_a_comment6c1,
            'question6c2' => $question6c2,
            'fin_eva_a_comment6c2' => $fin_eva_a_comment6c2,
            'fin_eva_a_comment6c3' => $fin_eva_a_comment6c3,
            'question6d' => $question6d,
            'fin_eva_a_comment6d' => $fin_eva_a_comment6d,
            'question6e' => $question6e,
            'fin_eva_a_comment6e' => $fin_eva_a_comment6e,
            'question7a1' => $question7a1,
            'fin_eva_a_comment7a1' => $fin_eva_a_comment7a1,
            'question7a2' => $question7a2,
            'fin_eva_a_comment7a2' => $fin_eva_a_comment7a2,
            'question7b1' => $question7b1,
            'fin_eva_a_comment7b1' => $fin_eva_a_comment7b1,
            'question7b2' => $question7b2,
            'fin_eva_a_comment7b2' => $fin_eva_a_comment7b2,
            'question7b3' => $question7b3,
            'fin_eva_a_comment7b3' => $fin_eva_a_comment7b3,
            'question7c' => $question7c,
            'fin_eva_a_comment7c' => $fin_eva_a_comment7c,
            'question7d' => $question7d,
            'fin_eva_a_comment7d' => $fin_eva_a_comment7d,
            'fin_eva_a_comment8a' => $fin_eva_a_comment8a,
            'fin_eva_a_comment8b' => $fin_eva_a_comment8b,
            'question8c' => $question8c,
            'fin_eva_a_comment8c' => $fin_eva_a_comment8c,
            'question8d' => $question8d,
            'fin_eva_a_comment8d' => $fin_eva_a_comment8d,
            'fin_eva_a_comment8e' => $fin_eva_a_comment8e,
            'fin_eva_a_comment8f' => $fin_eva_a_comment8f,
        ];  
    }
}
