<!-- SUPERINTENDENT'S VISITATION REPORT
areahead_district
areahead_area
areahead_local
areahead_status
areahead_comment1
areahead_comment2
areahead_comment3
areahead_comment4
areahead_comment5
areahead_comment6
areahead_question7
areahead_question8
areahead_question9
areahead_question10
areahead_question11
areahead_question12
areahead_question13
areahead_question14
areahead_comment14
areahead_question15
areahead_comment15
areahead_comment16
areahead_question17
areahead_comment17
areahead_comment18
areahead_comment19
areahead_comment20
areahead_comment21
areahead_pastors
areahead_elders
areahead_deacons
areahead_deaconesses
areahead_adult_males
areahead_adult_females
areahead_children
areahead_youth
areahead_total_att
areahead_tithe_payers
areahead_active_tithe_payers
areahead_tithes_paid
areahead_oferring
areahead_any_oferring
areahead_total_tithe_off
areahead_apostle
areahead_pastor -->


<!-- AREA SUPERINTENDENTS' DIRECT QUESTIONNAIRE
areasupq_name
areasupq_dob
areasupq_year
areasupq_date_of_report
areasupq_wife
areasupq_children
areasupq_child_age
areasupq_comment1
areasupq_comment2
areasupq_comment3
areasupq_comment4
areasupq_comment5
areasupq_comment6
areasupq_comment7
areasupq_comment8
areasupq_comment9
areasupq_name_sup -->


COMMUNITY IMPRESSION  REPORT
commrep_district
commrep_area
commrep_local
commrep_status
commrep_comment1
commrep_comment2
commrep_question3
commrep_comment3
commrep_question4
commrep_comment4
commrep_question5
commrep_comment5
commrep_question6
commrep_comment6
commrep_question7
commrep_comment7
commrep_question8
commrep_comment8
commrep_question9
commrep_comment9
commrep_question10
commrep_comment10
commrep_question11
commrep_comment11

DISTRICT OFFICERS LEVEL QUESTIONNAIRE
dlm_district
dlm_area
dlm_local
dlm_status
dlm_question1
dlm_comment1
dlm_question2
dlm_comment2
dlm_question3
dlm_comment3
dlm_question4
dlm_comment4
dlm_question5
dlm_comment5
dlm_question6
dlm_comment6
dlm_question7
dlm_comment7
dlm_question8
dlm_comment8
dlm_question9
dlm_comment9
dlm_question10
dlm_comment10
dlm_question11
dlm_comment11
dlm_question12
dlm_comment12


DISTRICT PASTORS' DIRECT QUESTIONNAIR
pastorques_name
pastorques_dob
pastorques_year
pastorques_stay_length
pastorques_wife
pastorques_children
pastorques_child_age
pastorques_child_station
pastorques_comment1
pastorques_comment2
pastorques_comment3
pastorques_comment4
pastorques_comment5
pastorques_comment6
pastorques_comment7
pastorques_comment8
pastorques_comment9
pastorques_comment10
pastorques_comment11
pastorques_comment12
pastorques_comment13
pastorques_comment14
pastorques_name_dist


DISTRICT PASTOR'S VISITATION REPORT
distpast_district
distpast_area
distpast_local
distpast_status
distpast_comment1
distpast_comment2
distpast_comment3
distpast_comment4
distpast_comment5
distpast_question6
distpast_question7
distpast_question8
distpast_question9
distpast_question10
distpast_question11
distpast_question12
distpast_question13
distpast_comment13
distpast_comment14
distpast_comment15
distpast_comment16
distpast_comment17
distpast_comment18
distpast_comment19
distpast_comment20
distpast_pastors
distpast_elders
distpast_deacons
distpast_deaconesses
distpast_adult_males
distpast_adult_females
distpast_children
distpast_youth
distpast_total_att
distpast_tithe_payers
distpast_active_tithe_payers
distpast_officers_tithe_payers
distpast_tithes_paid
distpast_oferring
distpast_any_oferring
distpast_total_tithe_off
distpast_pastor
distpast_p_elder


<!-- LOCAL QUESTIONNAIRE ON EVANGELISM
evange_district
evange_area
evange_local
evange_status
evange_question1
evange_comment1
evange_question2
evange_comment2
evange_question3
evange_comment3
evange_question4
evange_comment4
evange_question5
evange_comment5
evange_question6
evange_comment6
evange_question7
evange_comment7
evange_question8
evange_comment8
evange_question9
evange_comment9
evange_question10
evange_comment10
evange_question11
evange_comment11
evange_question12
evange_comment12
evange_question13
evange_comment13
evange_question14
evange_comment14
evange_question15
evange_comment15
evange_question16
evange_comment16
evange_question17
evange_comment17
evange_question18
evange_comment18
evange_name -->


LOCAL LEVEL QUESTIONNAIRE
llm_district
llm_area
llm_local
llm_status
llm_question1
llm_comment1
llm_question2
llm_comment2
llm_question3
llm_comment3
llm_question4
llm_comment4
llm_question5
llm_comment5
llm_question6
llm_comment6
llm_question7
llm_comment7
llm_question8
llm_comment8
llm_question9
llm_comment9
llm_question10
llm_comment10
llm_question11
llm_comment11
llm_question12
llm_comment12
llm_question13
llm_comment13
llm_question14
llm_comment14
llm_question15
llm_comment15
llm_question16
llm_comment16
llm_question17
llm_comment17
llm_question18
llm_comment18
llm_question19
llm_comment19
llm_question20
llm_comment20
llm_question21
llm_comment21
llm_question22
llm_comment22


MEMBER QUESTIONNAIRE
member_district
member_area
member_local
member_status
member_question1
member_comment1
member_question2
member_comment2
member_question3
member_comment3
member_question4
member_comment4
member_question5
member_comment5
member_question6
member_comment6
member_question7
member_comment7
member_question8
member_comment8
member_question9
member_comment9
member_question10
member_comment10
member_question11
member_comment11
member_question12
member_comment12
member_question13
member_comment13
member_question14
member_comment14
member_question15
member_comment15


MONITOR'S  REPORT
monirep_district
monirep_area
monirep_local
monirep_status
monirep_question1
monirep_comment1
monirep_question2
monirep_comment2
monirep_comment3
monirep_comment4
monirep_question5
monirep_comment5
monirep_question6
monirep_comment6
monirep_question7
monirep_question8
monirep_question9
monirep_question10
monirep_question11
monirep_question12
monirep_comment13
monirep_comment14
monirep_pastors
monirep_elders
monirep_deacons
monirep_deaconesses
monirep_adult_males
monirep_adult_females
monirep_children
monirep_youth
monirep_total_att
monirep_tithe_payers
monirep_tithes_paid
monirep_oferring
monirep_total_tithe_off


DB::unprepared("CREATE OR REPLACE VIEW v_w_areahead_reports as
            SELECT bloodtrans_id,
                
            FROM blood_transfussion_episodes;");


DB::unprepared('DROP VIEW IF EXISTS v_w_areahead_reports');