<!-- growth questionnire -->
growthque_district,
growthque_area,
growthque_local,
growthque_status,
growthque_question1,
growthque_comment1,
growthque_question2,
growthque_comment2,
growthque_question3,
growthque_comment3,
growthque_question4,
growthque_comment4,
growthque_question5,
growthque_comment5,
growthque_question6,
growthque_comment6,
growthque_question7,
growthque_comment7,
growthque_question8,
growthque_comment8,
growthque_question9,
growthque_comment9,
growthque_question10,
growthque_comment10,
growthque_question11,
growthque_comment11,
growthque_question12,
growthque_comment12,
growthque_question13,
growthque_comment13,
growthque_question14,
growthque_comment14,
growthque_question15,
growthque_comment15,
growthque_question16,
growthque_comment16,
growthque_question17,
growthque_comment17,
growthque_comment18,

<!-- Attendance ana -->
attn_district
attn_area
attn_local
attn_status
attn_month
attn_year
pastors1
pastors2
pastors3
pastors4
pastors5
pastors_total
elders1
elders2
elders3
elders4
elders5
elders_total
deacons1
deacons2
deacons3
deacons4
deacons5
deacons_total
deaconesses1
deaconesses2
deaconesses3
deaconesses4
deaconesses5
deaconesses_total
adult_males1
adult_males2
adult_males3
adult_males4
adult_males5
adult_males_total
adult_females1
adult_females2
adult_females3
adult_females4
adult_females5
adult_females_total
children1
children2
children3
children4
children5
children_total
youth1
youth2
youth3
youth4
youth5
youth_total
total_att
average_att

<!-- financial ass -->
fin_ass_district,
fin_ass_area,
fin_ass_local,
fin_ass_status,
fin_ass_month,
fin_ass_year,
fin_ass_tithe1,
fin_ass_offering1,
fin_ass_others1,
fin_ass_total1,
fin_ass_tithe2,
fin_ass_offering2,
fin_ass_others2,
fin_ass_total2,
fin_ass_tithe3,
fin_ass_offering3,
fin_ass_others3,
fin_ass_total3,
fin_ass_tithe4,
fin_ass_offering4,
fin_ass_others4,
fin_ass_total4,
fin_ass_tithe5,
fin_ass_offering5,
fin_ass_others5,
fin_ass_total5,
fin_ass_gdtotal,